
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating logo concepts based on user input.
 *
 * The flow takes business information, keywords, and style preferences as input and uses a
 * text-to-image model to generate multiple logo concepts.
 *
 * @interface GenerateLogoConceptsInput - The input type for the generateLogoConcepts function.
 * @interface GenerateLogoConceptsOutput - The output type for the generateLogoConcepts function.
 * @function generateLogoConcepts - A function that triggers the logo generation flow.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateLogoConceptsInputSchema = z.object({
  businessName: z.string().describe('The name of the business.'),
  industry: z.string().describe('The industry of the business.'),
  keywords: z.string().describe('Keywords describing the brand identity (may include Aesthetic, Emotional, Functional categories).'),
  preferredColorPalette: z
    .string()
    .optional()
    .describe('Optional preferred color palette (e.g., "Blue for trust, Gold for luxury").'),
  preferredLogoStyle:
    z.enum([
      'logomark',
      'wordmark',
      'lettermark',
      'combination',
      'emblem',
      'abstract',
      'mascot',
      'minimalist'
    ])
      .optional()
      .describe('Optional preferred logo style (e.g., minimalist, emblem).'),
  iconPlacement: z.enum(['above_text', 'left_of_text', 'right_of_text', 'below_text', 'no_icon', 'icon_only'])
    .optional()
    .describe('Optional preferred placement of the icon relative to the text.'),
  fontStyle: z.string().optional().describe('Optional preferred font style (e.g., "modern sans-serif", "elegant script", "No text").'),
  iconComplexity: z.enum(['simple', 'detailed']).optional().describe('Optional preferred icon complexity (e.g., simple, detailed).'),
  targetAudience: z.string().optional().describe('Optional description of the target audience (e.g., "Young professionals", "Eco-conscious consumers").'),
  inspirationReferences: z.string().optional().describe('Optional inspiration references (e.g., "Inspired by Nike’s simplicity", "Apple’s sleekness").'),
  usageContext: z.string().optional().describe('Optional primary usage context for the logo (e.g., "Digital only", "Print", "Merchandise", "Web, packaging, and print").'),
  negativeKeywords: z.string().optional().describe('Optional keywords or concepts to avoid (e.g., "No gradients", "Avoid cartoonish").'),
  variationInstructions: z.string().optional().describe('Optional instructions on how the generated variations should differ (e.g., "emphasize different fonts for each").'),
  numberOfLogos: z.number().default(4).describe('Number of logos to generate'),
});

export type GenerateLogoConceptsInput = z.infer<typeof GenerateLogoConceptsInputSchema>;

const GenerateLogoConceptsOutputSchema = z.object({
  logoUrls: z.array(z.string()).describe('Array of generated logo image URLs.'),
});

export type GenerateLogoConceptsOutput = z.infer<typeof GenerateLogoConceptsOutputSchema>;

export async function generateLogoConcepts(
  input: GenerateLogoConceptsInput
): Promise<GenerateLogoConceptsOutput> {
  return generateLogoConceptsFlow(input);
}

// This Handlebars prompt is not directly used for image generation in this flow's implementation,
// as image generation happens in a loop calling ai.generate directly.
// It's kept for potential future use or as a reference.
const prompt = ai.definePrompt({
  name: 'generateLogoConceptsPrompt',
  input: {
    schema: GenerateLogoConceptsInputSchema,
  },
  output: {
    schema: GenerateLogoConceptsOutputSchema,
  },
  prompt: `Generate logo concepts for a business named "{{businessName}}" in the "{{industry}}" industry.

The brand identity can be described using the following keywords: {{keywords}}.

{{#if preferredColorPalette}}
The preferred color palette is: {{preferredColorPalette}}.
{{/if}}

{{#if preferredLogoStyle}}
The preferred logo style is: {{preferredLogoStyle}}.
{{/if}}

{{#if iconPlacement}}
The preferred icon placement is: {{iconPlacement}}.
{{/if}}

{{#if fontStyle}}
The preferred font style is: {{fontStyle}}.
{{/if}}

{{#if iconComplexity}}
The preferred icon complexity is: {{iconComplexity}}.
{{/if}}

{{#if targetAudience}}
The target audience is: {{targetAudience}}.
{{/if}}

{{#if inspirationReferences}}
Inspiration references: {{inspirationReferences}}.
{{/if}}

{{#if usageContext}}
The primary usage context is: {{usageContext}}.
{{/if}}

{{#if negativeKeywords}}
Please avoid the following: {{negativeKeywords}}.
{{/if}}

{{#if variationInstructions}}
Instructions for variations: {{variationInstructions}}.
{{/if}}

Please generate {{numberOfLogos}} logo variations.
Output array of URLs for generated images in the format { "logoUrls": ["url1", "url2", "url3", "url4"] }.
`,
});

const generateLogoConceptsFlow = ai.defineFlow(
  {
    name: 'generateLogoConceptsFlow',
    inputSchema: GenerateLogoConceptsInputSchema,
    outputSchema: GenerateLogoConceptsOutputSchema,
  },
  async input => {
    const logoUrls: string[] = [];
    let baseImagePrompt = `Logo concept for a business named "${input.businessName}" in the "${input.industry}" industry. Brand identity keywords: ${input.keywords}.`;

    if (input.preferredColorPalette) {
      baseImagePrompt += ` Preferred color palette: ${input.preferredColorPalette}.`;
    }
    if (input.preferredLogoStyle) {
      baseImagePrompt += ` Preferred logo style: ${input.preferredLogoStyle}.`;
    }
    if (input.iconPlacement) {
      baseImagePrompt += ` Icon placement: ${input.iconPlacement}.`;
    }
    if (input.fontStyle) {
      baseImagePrompt += ` Font style: ${input.fontStyle}.`;
    }
    if (input.iconComplexity) {
      baseImagePrompt += ` Icon complexity: ${input.iconComplexity}.`;
    }
    if (input.targetAudience) {
      baseImagePrompt += ` Target audience: ${input.targetAudience}.`;
    }
    if (input.inspirationReferences) {
      baseImagePrompt += ` Inspiration references: ${input.inspirationReferences}.`;
    }
    if (input.usageContext) {
      baseImagePrompt += ` Primary usage context: ${input.usageContext}.`;
    }
    if (input.negativeKeywords) {
      baseImagePrompt += ` Avoid the following: ${input.negativeKeywords}.`;
    }


    for (let i = 0; i < input.numberOfLogos; i++) {
      let imagePrompt = baseImagePrompt;
      // Add variation instructions if provided
      if (input.variationInstructions) {
        imagePrompt += ` ${input.variationInstructions}`;
      }
      // Add a variation marker for subsequent logos
      if (i > 0) {
        imagePrompt += ` (variation ${i + 1})`;
      }
      

      const {media} = await ai.generate({
        model: 'googleai/gemini-2.0-flash-exp',
        prompt: imagePrompt,
        config: {
          responseModalities: ['TEXT', 'IMAGE'],
        },
      });
      logoUrls.push(media.url);
    }
    return {logoUrls: logoUrls};
  }
);
