// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating logo concepts based on user input.
 *
 * The flow takes business information and keywords as input and uses a text-to-image model
 * to generate multiple logo concepts.
 *
 * @interface GenerateLogoConceptsInput - The input type for the generateLogoConcepts function.
 * @interface GenerateLogoConceptsOutput - The output type for the generateLogoConcepts function.
 * @function generateLogoConcepts - A function that triggers the logo generation flow.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateLogoConceptsInputSchema = z.object({
  businessName: z.string().describe('The name of the business.'),
  industry: z.string().describe('The industry of the business.'),
  keywords: z.string().describe('Keywords describing the brand identity.'),
  preferredColorPalette: z
    .string()
    .optional()
    .describe('Optional preferred color palette.'),
  preferredLogoStyle:
    z.enum(['logomark', 'wordmark', 'combination mark', 'abstract'])
      .optional()
      .describe('Optional preferred logo style.'),
  numberOfLogos: z.number().default(4).describe('Number of logos to generate'),
});

export type GenerateLogoConceptsInput = z.infer<typeof GenerateLogoConceptsInputSchema>;

const GenerateLogoConceptsOutputSchema = z.object({
  logoUrls: z.array(z.string()).describe('Array of generated logo image URLs.'),
});

export type GenerateLogoConceptsOutput = z.infer<typeof GenerateLogoConceptsOutputSchema>;

export async function generateLogoConcepts(
  input: GenerateLogoConceptsInput
): Promise<GenerateLogoConceptsOutput> {
  return generateLogoConceptsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateLogoConceptsPrompt',
  input: {
    schema: GenerateLogoConceptsInputSchema,
  },
  output: {
    schema: GenerateLogoConceptsOutputSchema,
  },
  prompt: `Generate logo concepts for a business named "{{businessName}}" in the "{{industry}}" industry.

The brand identity can be described using the following keywords: {{keywords}}.

{{#if preferredColorPalette}}
The preferred color palette is: {{preferredColorPalette}}.
{{/if}}

{{#if preferredLogoStyle}}
The preferred logo style is: {{preferredLogoStyle}}.
{{/if}}

Please generate {{numberOfLogos}} logo variations.
Output array of URLs for generated images in the format { \"logoUrls\": [\"url1\", \"url2\", \"url3\", \"url4\"] }.
`,
});

const generateLogoConceptsFlow = ai.defineFlow(
  {
    name: 'generateLogoConceptsFlow',
    inputSchema: GenerateLogoConceptsInputSchema,
    outputSchema: GenerateLogoConceptsOutputSchema,
  },
  async input => {
    const logoUrls: string[] = [];
    for (let i = 0; i < input.numberOfLogos; i++) {
      const {media} = await ai.generate({
        model: 'googleai/gemini-2.0-flash-exp',
        prompt: `Generate logo concepts for a business named "${input.businessName}" in the "${input.industry}" industry.

        The brand identity can be described using the following keywords: ${input.keywords}.
        ${input.preferredColorPalette ? `The preferred color palette is: ${input.preferredColorPalette}.` : ''}
        ${input.preferredLogoStyle ? `The preferred logo style is: ${input.preferredLogoStyle}.` : ''}`,
        config: {
          responseModalities: ['TEXT', 'IMAGE'],
        },
      });
      logoUrls.push(media.url);
    }
    return {logoUrls: logoUrls};
  }
);
